spring:
  application:
    name: zuul-server
server:
  port : 9999

zuul:
  routes:
    offer:
      path: /offer/**
      url: http://65.2.123.169:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://65.2.123.169/:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://65.2.123.169:1003
    cart:
      path: /cart/**
      url: http://65.2.123.169:1004/api/v1
    shoe-service:
      path: /shoeapi/**
      serviceId: shoe-client
    offer-service:
      path: /offerapi/**
      serviceId: offers-client
    cart-service:
      path: /cartapi/**
      serviceId: cart-client